# Generated by Django 3.2.6 on 2021-08-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default=1, upload_to='img/product'),
            preserve_default=False,
        ),
    ]
